vim.api.nvim_set_keymap('n', '<space>ww', ':FocusSplitNicely<CR>', { silent = true, noremap = true })
vim.api.nvim_set_keymap('n', '<C-u>', ':wincmd k<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-d>', ':wincmd j<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<Space>wr', ':FocusSplitLeft<CR>', { silent = true, noremap = true })
vim.api.nvim_set_keymap('n', '<Space>wd', ':FocusSplitDown<CR>', { silent = true, noremap = true })
vim.api.nvim_set_keymap('n', '<Space>wu', ':FocusSplitUp<CR>', { silent = true, noremap = true })
vim.api.nvim_set_keymap('n', '<Space>wl', ':FocusSplitRight<CR>', { silent = true, noremap = true })
