vim.api.nvim_set_keymap('n', '<c-w>', ':FocusSplitNicely<CR>', { silent = true, noremap = true })
vim.api.nvim_set_keymap('n', '<C-u>', ':wincmd k<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<C-d>', ':wincmd j<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<c-b>', ':FocusSplitLeft<CR>', { silent = true, noremap = true })
vim.api.nvim_set_keymap('n', '<c-n>', ':FocusSplitDown<CR>', { silent = true, noremap = true })
vim.api.nvim_set_keymap('n', '<c-m>', ':FocusSplitUp<CR>', { silent = true, noremap = true })
vim.api.nvim_set_keymap('n', '<c-,>', ':FocusSplitRight<CR>', { silent = true, noremap = true })
