--vim.o.foldcolumn = "1"
--vim.o.foldlevel = 99
--vim.o.foldlevelstart = 99
--vim.o.foldenable = true
--
--vim.keymap.set("n", "zO", require("ufo").openAllFolds)
--vim.keymap.set("n", "zC", require("ufo").closeAllFolds)
--vim.keymap.set("n", "zo", require("ufo").openFoldsExceptKinds)
--vim.keymap.set("n", "zC", require("ufo").closeFoldsWith)
--
--require("ufo").setup()
